name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  installAndTest:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: ./install.sh
