name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  install on ubuntu 18:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: sudo apt-get remove msodbcsql17 -y && sudo ./install.sh -f
        
  install on ubuntu 20:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: sudo apt-get remove msodbcsql17 -y && sudo ./install.sh -f